<?php
namespace Modules\Rapat\Database\Seeders;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PegawaiSeederTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();
        DB::table('pegawais')->insert([
            [
                'nip'             => '1943345',
                'nama'            => 'PIMPINAN',
                'staff'           => 4,
                'jurusan'         => 4,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => null,
                'status_karyawan' => 5,
                'username'        => 'direktur',
                'noid'            => null,
            ],
            [
                'nip'             => '1943345345',
                'nama'            => 'DEVIT SUWARDIYANTO',
                'staff'           => 4,
                'jurusan'         => 4,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => null,
                'status_karyawan' => 5,
                'username'        => 'devit',
                'noid'            => null,
            ],
            [
                'nip'             => '195602221988111001',
                'nama'            => 'ASMUJI',
                'staff'           => 4,
                'jurusan'         => 4,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => null,
                'status_karyawan' => 5,
                'username'        => 'tefa',
                'noid'            => null,
            ],
            [
                'nip'             => '197601222021211001',
                'nama'            => 'MOH. DIMYATI AYATULLAH',
                'staff'           => 4,
                'jurusan'         => 1,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.Kom.',
                'status_karyawan' => 7,
                'username'        => 'dimdim',
                'noid'            => 1,
            ],
            [
                'nip'             => '198801182021211001',
                'nama'            => 'JAENI',
                'staff'           => 14,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => null,
                'status_karyawan' => 7,
                'username'        => 'jaeni',
                'noid'            => 3,
            ],
            [
                'nip'             => '198403052021212004',
                'nama'            => 'DIANNI YUSUF',
                'staff'           => 4,
                'jurusan'         => 1,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.Kom., M.Kom.',
                'status_karyawan' => 7,
                'username'        => 'dianni',
                'noid'            => 4,
            ],
            [
                'nip'             => '198310202014042001',
                'nama'            => 'EKA MISTIKO RINI',
                'staff'           => 4,
                'jurusan'         => 1,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.Kom, M.Kom.',
                'status_karyawan' => 5,
                'username'        => 'eka',
                'noid'            => 7,
            ],
            [
                'nip'             => '197806132014041001',
                'nama'            => 'MUHAMMAD FUAD ALHARIS',
                'staff'           => 4,
                'jurusan'         => 1,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => 5,
                'username'        => 'haris',
                'noid'            => 8,
            ],
            [
                'nip'             => '198401142019032006',
                'nama'            => 'ERNA SURYANI',
                'staff'           => 4,
                'jurusan'         => 3,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.Eng.',
                'status_karyawan' => 5,
                'username'        => 'erna',
                'noid'            => 10,
            ],
            [
                'nip'             => '197905302021212005',
                'nama'            => 'QURROTA A\'YUN',
                'staff'           => 7,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.Ak.',
                'status_karyawan' => 7,
                'username'        => 'yuyun',
                'noid'            => 11,
            ],
            [
                'nip'             => '198601082021212003',
                'nama'            => 'NIRMALA AYU NINGTYAS',
                'staff'           => 7,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E.',
                'status_karyawan' => 7,
                'username'        => 'nirmala',
                'noid'            => 14,
            ],
            [
                'nip'             => '197108272021211002',
                'nama'            => 'ENES ARIYANTO SANDI',
                'staff'           => 4,
                'jurusan'         => 3,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.M.',
                'status_karyawan' => 7,
                'username'        => 'enes',
                'noid'            => 16,
            ],
            [
                'nip'             => '198212262021211001',
                'nama'            => 'DENY SIGIT PRIYONO',
                'staff'           => 24,
                'jurusan'         => 4,
                'prodi'           => 11,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E.',
                'status_karyawan' => 7,
                'username'        => 'sigit',
                'noid'            => 17,
            ],
            [
                'nip'             => '198501222021211001',
                'nama'            => 'SISWO HANDOKO',
                'staff'           => 7,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T.',
                'status_karyawan' => 7,
                'username'        => 'siswo',
                'noid'            => 18,
            ],
            [
                'nip'             => '198106072021212007',
                'nama'            => 'YUNI ULFIYATI',
                'staff'           => 4,
                'jurusan'         => 3,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => 7,
                'username'        => 'yuni',
                'noid'            => 19,
            ],
            [
                'nip'             => '198304132021211003',
                'nama'            => 'ABDUL ROHMAN',
                'staff'           => 4,
                'jurusan'         => 2,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'ST., MT',
                'status_karyawan' => 7,
                'username'        => 'rahman',
                'noid'            => 20,
            ],
            [
                'nip'             => '197305312021212004',
                'nama'            => 'ENNY PURWATI',
                'staff'           => 7,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.Sos.',
                'status_karyawan' => 7,
                'username'        => 'enny',
                'noid'            => 21,
            ],
            [
                'nip'             => '198208072021211005',
                'nama'            => 'DIAN RIDLO PAMUJI',
                'staff'           => 4,
                'jurusan'         => 2,
                'prodi'           => 5,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => 7,
                'username'        => 'dian',
                'noid'            => 22,
            ],
            [
                'nip'             => '198611022014041001',
                'nama'            => 'PRIO WIDHIA FAJAR',
                'staff'           => 19,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E.',
                'status_karyawan' => 5,
                'username'        => 'prio',
                'noid'            => 23,
            ],
            [
                'nip'             => '197903112021211002',
                'nama'            => 'MOHAMMAD ABDUL WAHID',
                'staff'           => 4,
                'jurusan'         => 2,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => 7,
                'username'        => 'abdul',
                'noid'            => 24,
            ],
            [
                'nip'             => '198712202021211001',
                'nama'            => 'HAIRUL SALAM',
                'staff'           => 7,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T.',
                'status_karyawan' => 7,
                'username'        => 'hairul',
                'noid'            => 25,
            ],
            [
                'nip'             => '198205072021211007',
                'nama'            => 'CHAIRUL ANAM',
                'staff'           => 4,
                'jurusan'         => 2,
                'prodi'           => 5,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => 7,
                'username'        => 'anam',
                'noid'            => 27,
            ],
            [
                'nip'             => '198708272024211012',
                'nama'            => 'AGUS PRIYO UTOMO',
                'staff'           => 4,
                'jurusan'         => 1,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.ST., M.Tr.Kom.',
                'status_karyawan' => 6,
                'username'        => 'banksonk',
                'noid'            => 30,
            ],
            [
                'nip'             => '198301032021212008',
                'nama'            => 'ARIADNE IKA MAHARANI',
                'staff'           => 7,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'A.Md., S.E.',
                'status_karyawan' => 7,
                'username'        => 'miss_inne',
                'noid'            => 31,
            ],
            [
                'nip'             => '199112102021211002',
                'nama'            => 'FARNAS ADY PRAMONO',
                'staff'           => 7,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E.',
                'status_karyawan' => 7,
                'username'        => 'acil',
                'noid'            => 32,
            ],
            [
                'nip'             => '198505172015041003',
                'nama'            => 'ZULIS ERWANTO',
                'staff'           => 4,
                'jurusan'         => 3,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => '5',
                'username'        => 'zulis',
                'noid'            => '35',
            ],
            [
                'nip'             => '198106232024211007',
                'nama'            => 'DRIYANTO WAHYU WICAKSONO',
                'staff'           => 4,
                'jurusan'         => 3,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E., M.ST.',
                'status_karyawan' => '2',
                'username'        => 'dwahyu',
                'noid'            => '36',
            ],
            [
                'nip'             => '198403312019031007',
                'nama'            => 'MIRZA GHULAM RIFQI',
                'staff'           => 4,
                'jurusan'         => 3,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'ST., MST.',
                'status_karyawan' => '5',
                'username'        => 'mrifqi',
                'noid'            => '37',
            ],
            [
                'nip'             => '197509272021211002',
                'nama'            => 'HERMAN YULIANDOKO',
                'staff'           => 4,
                'jurusan'         => 1,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => '7',
                'username'        => 'herman',
                'noid'            => '40',
            ],
            [
                'nip'             => '198404032019032012',
                'nama'            => 'VIVIEN ARIEF WARDHANY',
                'staff'           => 4,
                'jurusan'         => 1,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => '5',
                'username'        => 'vivien',
                'noid'            => '42',
            ],
            [
                'nip'             => '197704042021211004',
                'nama'            => 'DEDY HIDAYAT KUSUMA',
                'staff'           => 4,
                'jurusan'         => 1,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.Cs.',
                'status_karyawan' => '7',
                'username'        => 'dedy',
                'noid'            => '44',
            ],
            [
                'nip'             => '198711032021212001',
                'nama'            => 'DIAN MUJIANI',
                'staff'           => 24,
                'jurusan'         => 1,
                'prodi'           => 4,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E.',
                'status_karyawan' => '7',
                'username'        => 'dianmjn',
                'noid'            => '45',
            ],
            [
                'nip'             => '198707072021031010',
                'nama'            => 'GALANG SANDY PRAYOGO',
                'staff'           => 4,
                'jurusan'         => 2,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => '5',
                'username'        => 'galang',
                'noid'            => '46',
            ],
            [
                'nip'             => '197506252021211003',
                'nama'            => 'SUBONO',
                'staff'           => 4,
                'jurusan'         => 1,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => '7',
                'username'        => 'bono',
                'noid'            => '47',
            ],
            [
                'nip'             => '198907072021212001',
                'nama'            => 'DEVI MAHDALENA',
                'staff'           => 35,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E.',
                'status_karyawan' => '7',
                'username'        => 'devi',
                'noid'            => '49',
            ],
            [
                'nip'             => '198301192021211006',
                'nama'            => 'MOH. NUR SHODIQ',
                'staff'           => 4,
                'jurusan'         => 1,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => '7',
                'username'        => 'shodiq',
                'noid'            => '50',
            ],
            [
                'nip'             => '198801152021211002',
                'nama'            => 'PANCA RIZA SUNANDAR',
                'staff'           => 24,
                'jurusan'         => 2,
                'prodi'           => 5,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E.',
                'status_karyawan' => '7',
                'username'        => 'panca',
                'noid'            => '53',
            ],
            [
                'nip'             => '198604202021211001',
                'nama'            => 'GINANJAR EKA SASMITA',
                'staff'           => 2,
                'jurusan'         => 3,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'A.Md.',
                'status_karyawan' => '7',
                'username'        => 'ginanjar',
                'noid'            => '55',
            ],
            [
                'nip'             => '198606152021212003',
                'nama'            => 'ELY TRIANA SARI',
                'staff'           => 4,
                'jurusan'         => 2,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.Pd., M.Pd.',
                'status_karyawan' => '7',
                'username'        => 'elly',
                'noid'            => '56',
            ],
            [
                'nip'             => '198403112019031005',
                'nama'            => 'ENDI SAILUL HAQ',
                'staff'           => 4,
                'jurusan'         => 1,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.Kom.',
                'status_karyawan' => '5',
                'username'        => 'endi',
                'noid'            => '58',
            ],
            [
                'nip'             => '198605212015041002',
                'nama'            => 'M. SHOFI\'UL AMIN',
                'staff'           => 4,
                'jurusan'         => 3,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => 'Ir.',
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => '5',
                'username'        => 'shofi',
                'noid'            => '60',
            ],
            [
                'nip'             => '198704272014041001',
                'nama'            => 'UBNU FAJAR KARIMMULLOH',
                'staff'           => 3,
                'jurusan'         => 3,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'A.Md.',
                'status_karyawan' => '5',
                'username'        => 'ubnu',
                'noid'            => '61',
            ],
            [
                'nip'             => '198406142014041001',
                'nama'            => 'EKO SLAMET RIYADI',
                'staff'           => 3,
                'jurusan'         => 2,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'A.Md.',
                'status_karyawan' => '5',
                'username'        => 'ekochouw',
                'noid'            => '63',
            ],
            [
                'nip'             => '198107102021211007',
                'nama'            => 'TRI PRASETYO',
                'staff'           => 7,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.Ab.',
                'status_karyawan' => '7',
                'username'        => 'treepras',
                'noid'            => '64',
            ],
            [
                'nip'             => '198405122021211003',
                'nama'            => 'MOCHAMAD AROFI',
                'staff'           => 2,
                'jurusan'         => 2,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T.',
                'status_karyawan' => '7',
                'username'        => 'roby',
                'noid'            => '66',
            ],
            [
                'nip'             => '198706232019032009',
                'nama'            => 'IKA YUNIWATI',
                'staff'           => 4,
                'jurusan'         => 2,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.Pd., M.Si.',
                'status_karyawan' => '5',
                'username'        => 'ika',
                'noid'            => '67',
            ],
            [
                'nip'             => '198110072021212006',
                'nama'            => 'DWI WAHYUNI',
                'staff'           => 7,
                'jurusan'         => 5,
                'prodi'           => 14,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E.',
                'status_karyawan' => '7',
                'username'        => 'dwiyuni',
                'noid'            => '68',
            ],
            [
                'nip'             => '199111012021212001',
                'nama'            => 'NOVINARI BUDI EKAWATI',
                'staff'           => 7,
                'jurusan'         => 0,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E.',
                'status_karyawan' => '7',
                'username'        => 'novi',
                'noid'            => '69',
            ],
            [
                'nip'             => '198103232014041001',
                'nama'            => 'ARYA PRAMUDITA',
                'staff'           => 7,
                'jurusan'         => 1,
                'prodi'           => 6,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E.',
                'status_karyawan' => '5',
                'username'        => 'pramudita',
                'noid'            => '71',
            ],
            [
                'nip'             => '198612312019032016',
                'nama'            => 'WAHYU NARIS WARI',
                'staff'           => 4,
                'jurusan'         => 3,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.T., M.T.',
                'status_karyawan' => '5',
                'username'        => 'Nariswari',
                'noid'            => 75,
            ],
            [
                'nip'             => '198605182014042001',
                'nama'            => 'IMAROTUL HUSNA',
                'staff'           => 18,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E.',
                'status_karyawan' => '5',
                'username'        => 'imahusna',
                'noid'            => 76,
            ],
            [
                'nip'             => '198603052024211014',
                'nama'            => 'FARIZQI PANDUARDI',
                'staff'           => 4,
                'jurusan'         => 1,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.ST., M.T.',
                'status_karyawan' => '2',
                'username'        => 'farisqi',
                'noid'            => 79,
            ],
            [
                'nip'             => '198803302024212025',
                'nama'            => 'EVA ANISA',
                'staff'           => 24,
                'jurusan'         => 3,
                'prodi'           => 1,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'A.Md.',
                'status_karyawan' => '2',
                'username'        => 'eva',
                'noid'            => 81,
            ],
            [
                'nip'             => '198305222021211003',
                'nama'            => 'TRI PRASETIA',
                'staff'           => 7,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'A.Md.',
                'status_karyawan' => '7',
                'username'        => 'trip',
                'noid'            => '83',
            ],
            [
                'nip'             => '196910242021211003',
                'nama'            => 'ANANG SUPRIHARTONO',
                'staff'           => 14,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => null,
                'status_karyawan' => '7',
                'username'        => 'anangsuprihartono',
                'noid'            => '95',
            ],
            [
                'nip'             => '197711212010122001',
                'nama'            => 'SISKA RAHMAWATI',
                'staff'           => 18,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => null,
                'status_karyawan' => null,
                'username'        => null,
                'noid'            => '99',
            ],
            [
                'nip'             => '198307132010122003',
                'nama'            => 'WAHYU YULIANINGSIH',
                'staff'           => 18,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.Si.',
                'status_karyawan' => '5',
                'username'        => 'yuli',
                'noid'            => '100',
            ],
            [
                'nip'             => '196407141990021001',
                'nama'            => 'MUHAMMAD TOYIB',
                'staff'           => 21,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'L',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E., M.M.',
                'status_karyawan' => '5',
                'username'        => 'mthoy',
                'noid'            => '101',
            ],
            [
                'nip'             => '197405142001122002',
                'nama'            => 'URI ANJARWATI',
                'staff'           => 7,
                'jurusan'         => null,
                'prodi'           => null,
                'jenis_kelamin'   => 'P',
                'gelar_dpn'       => null,
                'gelar_blk'       => 'S.E., M.M.',
                'status_karyawan' => '5',
                'username'        => 'uri',
                'noid'            => '102',
            ],
        ]);
    }
}
